@startuml

class Tag {
    name
    loveLevel
}

class Topic {
    title
    describe
    createdUser
    followed
    tags: Tag[]
    followers: User[]
    followerCount
}

class User {
    name
}

Tag "*" <- "1" User : love

Topic "*" <- "1" User : follow

@enduml

followTag()
unFollowTag()
followTopic()
unFollowTopic()
createTag()