@startuml

class Tag {
    name
    loveLevel
    followed
}

class Topic {
    name
    describe
    followed
    tags: Tag[]
}

class User {
    name
}

Tag "*" <- "1" User : love

Topic "*" <- "1" User : follow

@enduml

followTag()
unFollowTag()
followTopic()
unFollowTopic()
createTag()